apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: log-pipeline
data:
  logstash.conf: |
    input {
      http {
        port => 8080
      }
    }
    filter {
      json {
        source => "message"
        skip_on_invalid_json => true
      }
    }
    output {
      s3 {
        region => "ap-southeast-1"
        bucket => "cyn-datalake-test"
        time_file => 5
        codec => "json_lines"
        canned_acl => "private"
      }
    }
 
