apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: log-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: aungkhantmaung0606/logstash-opensearch:9.0.2
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: pipeline
          mountPath: /usr/share/logstash/pipeline/logstash.conf
          subPath: logstash.conf
      volumes:
      - name: pipeline
        configMap:
          name: logstash-config
