apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: log-pipeline
data:
  logstash.conf: |
    input {
      http {
        port => 8080
      }
    }
    filter {
      json {
        source => "message"
        skip_on_invalid_json => true
      }
    }
    output {
      opensearch {
        hosts => ["http://opensearch:9200"]
        index => "logs-%{+YYYY.MM.dd}"
        user => "admin"
        password => "Strongpassword123!"
        ssl => false
      }
    }
