apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: log-pipeline
data:
  logstash.conf: |
    input {
      http {
        port => 8080
      }
    }
    output {
      opensearch {
        hosts => ["http://opensearch.log-pipeline.svc.cluster.local:9200"]
        index => "logs-%{+YYYY.MM.dd}"
        ssl => false
      }
    }
