apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: log-pipeline
data:
  logstash.conf: |
    input {
      http {
        port => 8080
      }
    }
    filter {
      json {
        source => "message"
        skip_on_invalid_json => true
      }
    }
    output {
      opensearch {
        hosts => ["http://opensearch:31561"]
        index => "logs-%{+YYYY.MM.dd}"
        user => "admin"
        password => "Strongpassword123!"
        ssl => false
      }
      s3 {
        access_key_id => "${AWS_ACCESS_KEY_ID}"
        secret_access_key => "${AWS_SECRET_ACCESS_KEY}"
        region => "ap-southeast-1"
        bucket => "cyn-datalake-test"
        temporary_directory => "/tmp/logstash"
        time_file => 1
        codec => "json"
        canned_acl => "private"
      }
    }
 
