apiVersion: v1
kind: ConfigMap
metadata:
  name: opensearch
  namespace: log-pipeline
data:
  template-logs.json: |
    {
      "index_patterns": ["logs-*"],
      "template": {
        "settings": {
          "index": {
            "number_of_shards": "1",
            "number_of_replicas": "2",
            "refresh_interval": "10s"
          }
        },
        "mappings": {
          "date_detection": false,
          "properties": {
            "@timestamp": {
              "type": "date"
            }
          }
        }
      },
      "version": 1
    }
