apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opensearch
  namespace: log-pipeline
spec:
  serviceName: opensearch
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      containers:
      - name: opensearch
        image: opensearchproject/opensearch:2.14.0
        ports:
        - containerPort: 9200
        env:
        - name: discovery.type
          value: single-node
        - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
          value: "admin"  # ❗ Change to a strong password
        - name: plugins.security.ssl.http.enabled
          value: "false"  # Optional: disable HTTPS for development
        - name: plugins.security.allow_unsafe_democertificates
          value: "true"   # Use demo certs (for dev only)
        - name: plugins.security.allow_default_init_securityindex
          value: "true"
        - name: OPENSEARCH_JAVA_OPTS
          value: "-Xms512m -Xmx512m"

        volumeMounts:
        - name: data
          mountPath: /usr/share/opensearch/data
      volumes:
      - name: data
        emptyDir: {}
