apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: log-pipeline
spec:
  selector:
    app: opensearch
  ports:
  - port: 9200
    targetPort: 9200
    nodePort: 31561
    name: http
    protocol: TCP
