apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opensearch
  namespace: log-pipeline
spec:
  serviceName: opensearch
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      containers:
      - name: opensearch
        image: opensearchproject/opensearch:2.14.0
        ports:
        - containerPort: 9200
        env:
        - name: discovery.type
          value: single-node
        - name: plugins.security.disabled
          value: "true"
        - name: OPENSEARCH_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
              value: "StrongPassword123!"  
        volumeMounts:
        - name: data
          mountPath: /usr/share/opensearch/data
      volumes:
      - name: data
        emptyDir: {}
